export enum SkillCategory {
  L = 'Language',
  S = 'Soft Skill',
  F = 'Framework',
  U = 'Utility',
  E = 'Experience',
  D = 'Design',
}

interface Skill {
  name: string;
  category: SkillCategory;
  level: number;
  iconSrc: string;
  description: string;
}

export const Skills: Skill[] = [
  {
    name: 'Python',
    category: SkillCategory.L,
    level: 2,
    iconSrc: '',
    description: '',
  },
  {
    name: 'Django',
    category: SkillCategory.F,
    level: 1,
    iconSrc: '',
    description: '',
  },
  {
    name: 'JavaScript',
    category: SkillCategory.L,
    level: 5,
    iconSrc: '',
    description: '',
  },
  {
    name: 'React',
    category: SkillCategory.F,
    level: 4,
    iconSrc: '',
    description: '',
  },
  {
    name: 'Redux',
    category: SkillCategory.F,
    level: 2,
    iconSrc: '',
    description: '',
  },
  {
    name: 'TypeScript',
    category: SkillCategory.L,
    level: 1,
    iconSrc: '',
    description: '',
  },
  {
    name: 'CSS',
    category: SkillCategory.L,
    level: 3,
    iconSrc: '',
    description: '',
  },
  {
    name: 'HTML5',
    category: SkillCategory.L,
    level: 6,
    iconSrc: '',
    description: '',
  },
  {
    name: 'Git',
    category: SkillCategory.U,
    level: 5,
    iconSrc: '',
    description: '',
  },
  {
    name: 'Not Being An Asshole',
    category: SkillCategory.S,
    level: 14,
    iconSrc: '',
    description: 'Diplomatic? Yes. Doormat? Hell no.',
  },
  {
    name: 'Creativity',
    category: SkillCategory.S,
    level: 20,
    iconSrc: '',
    description: 'I love making unexpected and awesome things.',
  },
  {
    name: 'Bootstrap',
    category: SkillCategory.F,
    level: 3,
    iconSrc: '',
    description: '',
  },
  {
    name: 'Written & Verbal Communication',
    category: SkillCategory.S,
    level: 17,
    iconSrc: '',
    description:
      'Nothing else to say about it. Because I omit needless words. Always.',
  },
  {
    name: 'Growth Mindset',
    category: SkillCategory.S,
    level: 12,
    iconSrc: '',
    description:
      "I'm a recovering perfectionist, seeking opportunities to maximize my learning by embracing failure.",
  },
  {
    name: 'GitHub',
    category: SkillCategory.U,
    level: 5,
    iconSrc: '',
    description:
      'I love optimizing my repos by including templates and utilizing the project management features of the site.',
  },
  {
    name: 'Azure DevOps',
    category: SkillCategory.U,
    level: 3,
    iconSrc: '',
    description: 'Always a sucker for a wicked cool project management system.',
  },
  {
    name: 'Grunt',
    category: SkillCategory.U,
    level: 7,
    iconSrc: '',
    description: '',
  },
  {
    name: 'Sass',
    category: SkillCategory.F,
    level: 7,
    iconSrc: '',
    description: '',
  },
  {
    name: 'WordPress',
    category: SkillCategory.U,
    level: 5,
    iconSrc: '',
    description: '',
  },
  {
    name: 'Drupal',
    category: SkillCategory.U,
    level: 5,
    iconSrc: '',
    description: '',
  },
  {
    name: 'SQL',
    category: SkillCategory.L,
    level: 7,
    iconSrc: '',
    description: '',
  },
  {
    name: 'RESTful API',
    category: SkillCategory.F,
    level: 5,
    iconSrc: '',
    description: '',
  },
  {
    name: 'Data Analysis',
    category: SkillCategory.E,
    level: 14,
    iconSrc: '',
    description: '',
  },
  {
    name: 'Scrum Methodology',
    category: SkillCategory.S,
    level: 9,
    iconSrc: '',
    description: 'Scrum Master Certified',
  },
  {
    name: 'Test Driven Development',
    category: SkillCategory.E,
    level: 3,
    iconSrc: '',
    description: '',
  },
  {
    name: 'Agile Software Development Practices',
    category: SkillCategory.E,
    level: 8,
    iconSrc: '',
    description: '',
  },
  {
    name: 'Research',
    category: SkillCategory.E,
    level: 16,
    iconSrc: '',
    description: '',
  },
  {
    name: 'Business Requirement Analysis & Design',
    category: SkillCategory.E,
    level: 12,
    iconSrc: '',
    description: '',
  },
  {
    name: 'Documentation',
    category: SkillCategory.E,
    level: 18,
    iconSrc: '',
    description: '',
  },
  {
    name: 'Technical Writing & Editing',
    category: SkillCategory.S,
    level: 16,
    iconSrc: '',
    description: '',
  },
  {
    name: 'Graphic Design',
    category: SkillCategory.D,
    level: 6,
    iconSrc: '',
    description: '',
  },
  {
    name: 'Digital Photography',
    category: SkillCategory.D,
    level: 18,
    iconSrc: '',
    description: '',
  },
  {
    name: 'Solving Problems',
    category: SkillCategory.S,
    level: 18,
    iconSrc: '',
    description: '',
  },
  {
    name: 'Process Optimization',
    category: SkillCategory.E,
    level: 14,
    iconSrc: '',
    description: '',
  },
  {
    name: 'Digital Ocean',
    category: SkillCategory.E,
    level: 2,
    iconSrc: '',
    description: '',
  },
  {
    name: 'Command Line',
    category: SkillCategory.L,
    level: 3,
    iconSrc: '',
    description: '',
  },
];
